" let Vundle manage Vundle
" required! 
" Bundle 'gmarik/vundle' "This does not work yet with submodules

Bundle 'gmarik/vundle'

" original repos on github
Bundle 'AutoTag'
Bundle 'Better-CSS-Syntax-for-Vim'
Bundle 'L9'
Bundle 'Lokaltog/vim-easymotion'
Bundle 'Lokaltog/vim-powerline'
Bundle 'Rename'
Bundle 'Tabular'
Bundle 'The-NERD-tree'
Bundle 'TwitVim'
Bundle 'adamnbowen/scss-syntax.vim'
Bundle 'c9s/cascading.vim'
Bundle 'chrismetcalf/vim-yankring'
Bundle 'clones/vim-autocomplpop'
Bundle 'closetag.vim'
Bundle 'comment.vim'
Bundle 'css_color.vim'
Bundle 'ervandew/snipmate.vim'
Bundle 'hallettj/jslint.vim'
Bundle 'imathis/vim-colors-solarized'
Bundle 'int3/vim-taglist-plus'
Bundle 'itspriddle/vim-jquery'
Bundle 'jayferd/eco.vim'
Bundle 'juvenn/mustache.vim'
Bundle 'kana/vim-textobj-user'
Bundle 'kien/ctrlp.vim'
Bundle 'kien/rainbow_parentheses.vim'
Bundle 'leshill/vim-json'
Bundle 'michaeljsmith/vim-indent-object'
Bundle 'molokai'
Bundle 'nelstrom/vim-textobj-rubyblock'
Bundle 'othree/html5.vim'
Bundle 'pangloss/vim-javascript'
Bundle 'pix/vim-align'
Bundle 'robgleeson/hammer.vim'
Bundle 'rstacruz/sparkup', {'rtp': 'vim/'}
Bundle 'scrooloose/nerdcommenter'
Bundle 'scrooloose/syntastic'
Bundle 'sdiehl/vim-coffee-script'
Bundle 'sickill/vim-pasta'
Bundle 'sjl/gundo.vim'
Bundle 'tpope/vim-abolish'
Bundle 'tpope/vim-cucumber'
Bundle 'tpope/vim-endwise'
Bundle 'tpope/vim-fugitive'
Bundle 'tpope/vim-git'
Bundle 'tpope/vim-haml'
Bundle 'tpope/vim-markdown'
Bundle 'tpope/vim-pathogen'
Bundle 'tpope/vim-rails'
Bundle 'tpope/vim-rails.git'
Bundle 'tpope/vim-rake'
Bundle 'tpope/vim-repeat'
Bundle 'tpope/vim-speeddating'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-unimpaired'
Bundle 'vlmonk/vim-rspec'
Bundle 'wzzrd/vim-matchit'
Bundle 'manalang/jshint.vim'
Bundle 'jamescarr/snipmate-nodejs'
Bundle 'guileen/vim-node'
Bundle 'vim-octopress'
" non github repos
Bundle 'git://git.wincent.com/command-t.git'

" BUNDLES ARCHIVE {{{
"  Bundle 'ervandew/supertab'
"  Bundle 'vim-stylus'
" }}}

